import chromadb
from chromadb.config import Settings
from chromadb.utils.embedding_functions import ONNXMiniLM_L6_V2
from typing import List
import json

from .document_processor import DocumentChunk

class VectorStore:
    """ChromaDB-based vector storage for document embeddings."""
    
    def __init__(self, collection_name: str = "manuals", persist_dir: str = "./chroma_db"):
        self.persist_dir = persist_dir
        
        # Initialize ChromaDB with persistence
        self.client = chromadb.PersistentClient(
            path=persist_dir,
            settings=Settings(
                anonymized_telemetry=False,
                allow_reset=True
            )
        )
        
        # Use ChromaDB's built-in ONNX embedding function (no PyTorch required)
        self.embedding_function = ONNXMiniLM_L6_V2()
        
        # Get or create collection with embedding function
        self.collection = self.client.get_or_create_collection(
            name=collection_name,
            metadata={"hnsw:space": "cosine"},
            embedding_function=self.embedding_function
        )
    
    def add_documents(self, chunks: List[DocumentChunk]) -> bool:
        """Add document chunks to vector store."""
        if not chunks:
            return False
        
        # Prepare batch
        ids = []
        documents = []
        metadatas = []
        
        for chunk in chunks:
            chunk_id = f"{chunk.manual_id}_{chunk.chunk_index}"
            ids.append(chunk_id)
            documents.append(chunk.text)
            
            # Metadata for retrieval and citations
            metadatas.append({
                "manual_id": chunk.manual_id,
                "manual_name": chunk.manual_name,
                "page_number": chunk.page_number,
                "chunk_index": chunk.chunk_index,
                "char_count": len(chunk.text),
                "has_metadata": json.dumps(chunk.metadata) if chunk.metadata else "{}"
            })
        
        # Add to collection - embeddings auto-generated by ChromaDB
        self.collection.add(
            ids=ids,
            documents=documents,
            metadatas=metadatas
        )
        
        return True
    
    def search(self, query: str, manual_id: str = None, top_k: int = 3) -> List[dict]:
        """Search for relevant chunks."""
        # Build filter
        where_filter = None
        if manual_id:
            where_filter = {"manual_id": manual_id}
        
        # Search - query embedding auto-generated by ChromaDB
        results = self.collection.query(
            query_texts=[query],
            n_results=top_k,
            where=where_filter,
            include=["documents", "metadatas", "distances"]
        )
        
        # Format results
        formatted = []
        if results['ids'] and results['ids'][0]:
            for i in range(len(results['ids'][0])):
                formatted.append({
                    "id": results['ids'][0][i],
                    "text": results['documents'][0][i],
                    "metadata": results['metadatas'][0][i],
                    "score": 1 - results['distances'][0][i]  # Convert distance to similarity
                })
        
        return formatted
    
    def delete_manual(self, manual_id: str) -> bool:
        """Delete all chunks for a manual."""
        try:
            self.collection.delete(where={"manual_id": manual_id})
            return True
        except Exception as e:
            print(f"Error deleting manual {manual_id}: {e}")
            return False
    
    def get_stats(self) -> dict:
        """Get collection statistics."""
        return {
            "total_chunks": self.collection.count(),
            "persist_directory": self.persist_dir
        }
    
    def is_ready(self) -> bool:
        """Check if vector store is ready."""
        try:
            self.collection.count()
            return True
        except Exception:
            return False
